#  > docker-compose -f docker/{{cookiecutter.__pkg_import_name}}_local/.devcontainer/docker-compose.yml up -V --detach --force-recreate --remove-orphans --build
#  > docker-compose -f docker/{{cookiecutter.__pkg_import_name}}_local/.devcontainer/docker-compose.yml down --volumes

version: "3.9"
services:
  mysql_sciops:
    environment:
      MYSQL_ROOT_PASSWORD: ${DJ_PASS:-simple}
      MYSQL_USER: djuser
      MYSQL_PASSWORD: djuser
    image: datajoint/mysql:5.7
    networks:
      {{cookiecutter.__pkg_import_name}}:
    platform: linux/amd64
    ports:
      - 6603:3306
    restart: always
    volumes:
      - sciops-sqldata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  devcontainer_env:
    build:
      context: ../../../.
      dockerfile: docker/{{cookiecutter.__pkg_import_name}}_local/.devcontainer/build/Dockerfile
      args:
        REPO_NAME: {{cookiecutter.github_repo}}
        WORKFLOW_VERSION: v0.0.0
    image: ghcr.io/iamamutt/{{cookiecutter.github_repo}}:latest
    depends_on:
      mysql_sciops:
        condition: service_healthy
    environment:
      DJ_HOST: mysql_sciops
      DJ_PASS: ${DJ_PASS:-simple}
      DJ_USER: ${DJ_USER:-root}
    init: true
    tty: true
    networks:
      {{cookiecutter.__pkg_import_name}}:
    ports:
      - 18888:8888
    volumes:
      - ../../..:/home/djuser/{{cookiecutter.github_repo}}
      - vscode:/home/djuser/.vscode-server/extensions
      - /home/djuser/{{cookiecutter.github_repo}}/.nox
      - /home/djuser/{{cookiecutter.github_repo}}/src/{{cookiecutter.__pkg_import_name}}.egg-info

  # MySQL GUI --------------
  # http://localhost:8087/
  # System: PostgreSQL
  # Server: mysql_sciops
  # Username: root
  # Password: simple
  adminer:
    environment:
      ADMINER_DEFAULT_SERVER: mysql_sciops
      ADMINER_DESIGN: nette
    image: adminer
    networks:
      {{cookiecutter.__pkg_import_name}}:
    ports:
      - target: 8080
        published: 8087
    restart: always
    depends_on:
      mysql_sciops:
        condition: service_started

networks:
  {{cookiecutter.__pkg_import_name}}:
    name: {{cookiecutter.__project_name}}-network

volumes:
  sciops-sqldata:
    name: {{cookiecutter.__project_name}}-vol-sciops-sqldata
  vscode:
    name: {{cookiecutter.__project_name}}-vol-vscode
