# Initial install:
#   > mamba env create -qvf environment.yml
# Update env:
#   > mamba env update -qvf environment.yml --prune
# Package install:
#   > flit install -s
# Remove env:
#   > mamba env remove -n {{cookiecutter.__pkg_import_name}}

name: {{cookiecutter.__pkg_import_name}}
channels:
  - conda-forge
  - defaults
dependencies:
  # Core environment dependencies
  - python=3.9.10
  - pip>21.3
  - flit>3.6,<4
  - mamba>0.21
