name: run-ci-jobs

on:
  push:
    branches: ["main"]

jobs:
  get_tag:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create a tag
        uses: mathieudutour/github-tag-action@v6.0
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          create_annotated_tag: false
          fetch_all_tags: true

  generate_datajoint-workflow:
    runs-on: ubuntu-latest
    needs: [get_tag]
    if: |
      always() &&
      (needs.get_tag.result == 'success') &&
      (github.ref_name == 'main') &&
      (github.ref_type == 'branch')
    outputs:
      artifact: ${{ steps.bake-cookies.outputs.artifact }}

    steps:
      - name: Checkout Repository for Local Action
        uses: actions/checkout@v3

      - name: Generate Content from 'datajoint-workflow' Template
        id: bake-cookies
        uses: ./.github/actions/bake-cookies
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: datajoint-workflow
          folder: science-institute_brain-lab
          cookiecutter_pkg: git+https://github.com/cookiecutter/cookiecutter tomli pyyaml
          new_tag: ${{ needs.get_tag.outputs.new_tag }}

  generate_basic-package:
    runs-on: ubuntu-latest
    needs: [get_tag]
    if: |
      always() &&
      (needs.get_tag.result == 'success') &&
      (github.ref_name == 'main') &&
      (github.ref_type == 'branch')
    outputs:
      artifact: ${{ steps.bake-cookies.outputs.artifact }}

    steps:
      - name: Checkout Repository for Local Action
        uses: actions/checkout@v3

      - name: Generate Content from 'basic-package' Template
        id: bake-cookies
        uses: ./.github/actions/bake-cookies
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: basic-package
          folder: datajoint_basic-package
          cookiecutter_pkg: git+https://github.com/cookiecutter/cookiecutter tomli pyyaml
          new_tag: ${{ needs.get_tag.outputs.new_tag }}



  make_release:
    runs-on: ubuntu-latest
    needs: [get_tag, generate_datajoint-workflow, generate_basic-package]
    if: |
      always() &&
      (needs.get_tag.result == 'success') &&
      (needs.generate_datajoint-workflow.result == 'success') &&
      (needs.generate_basic-package.result == 'success') &&

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Downloading 'datajoint-workflow' Artifact Content
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.generate_datajoint-workflow.outputs.artifact }}
          path: ${{ needs.generate_datajoint-workflow.outputs.artifact }}

      - name: Downloading 'basic-package' Artifact Content
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.generate_basic-package.outputs.artifact }}
          path: ${{ needs.generate_basic-package.outputs.artifact }}

      - run: |
          tar -zcf ${{ needs.generate_datajoint-workflow.outputs.artifact }}.tar.gz ${{ needs.generate_datajoint-workflow.outputs.artifact }}
          tar -zcf ${{ needs.generate_basic-package.outputs.artifact }}.tar.gz ${{ needs.generate_basic-package.outputs.artifact }}

      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.get_tag.outputs.new_tag }}
          name: ${{ github.ref_name }}-release ${{ needs.get_tag.outputs.new_tag }}
          body: ${{ needs.get_tag.outputs.changelog }}
          allowUpdates: true
          generateReleaseNotes: true
          artifacts: |
            ${{ needs.generate_datajoint-workflow.outputs.artifact }}.tar.gz
            ${{ needs.generate_basic-package.artifact }}.tar.gz
